# Generated by Django 5.1.1 on 2024-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.CharField(choices=[('factory', 'factory'), ('retail', 'retail network'), ('trader', 'individual entrepreneur')], default='factory', max_length=10, verbose_name='уровень'),
        ),
    ]
