# Generated by Django 5.1.1 on 2024-10-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
