# Generated by Django 5.1.1 on 2024-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукция', 'verbose_name_plural': 'продукция'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='seller',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='products', to='trading.product'),
        ),
    ]
