# Generated by Django 5.1.1 on 2024-10-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_product_options_rename_seller_supplier_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
    ]
